services:
  mssql-server:
    container_name: senukai-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'localDevelop1'
      ACCEPT_EULA: 'Y'
